apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "naavre-paas-frontend.fullname" . }}
  labels:
    {{- include "naavre-paas-frontend.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_BASE_PATH: "{{ .Values.conf.basePath }}"
  NAAVRE_CATALOGUE_SERVICE_URL: "{{ .Values.conf.services.naavreCatalogueServiceUrl }}"
  NEXTAUTH_URL: "https://{{ index (index .Values.ingress.hosts 0) "host" }}/{{ .Values.conf.basePath | trimAll "/" }}/api/auth"
  NEXTAUTH_URL_INTERNAL: "http://localhost:3000/{{ .Values.conf.basePath | trimAll "/" }}/api/auth"
  {{- if not .Values.conf.verifySSL }}
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  {{- end }}
