apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "naavre-paas-frontend.fullname" . }}
  labels:
    {{- include "naavre-paas-frontend.labels" . | nindent 4 }}
data:
  AUTH0_ID: "{{ .Values.conf.oidc.clientId | b64enc }}"
  AUTH0_SECRET: "{{ .Values.conf.oidc.clientSecret | b64enc }}"
  AUTH0_ISSUER: "{{ .Values.conf.oidc.issuerUrl | b64enc }}"
  NEXTAUTH_SECRET: "{{ .Values.conf.secret | b64enc }}"